site_name: Video Features Documentation
theme:
  name: material
  palette:
    primary: red
  features:
    - content.code.copy
repo_url: https://github.com/v-iashin/video_features
markdown_extensions:
  - admonition
  - mdx_truly_sane_lists
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
