# Model
feature_type: 'r21d'
model_name: 'r2plus1d_18_16_kinetics' # or 'r2plus1d_34_32_ig65m_ft_kinetics', or 'r2plus1d_34_8_ig65m_ft_kinetics'
stack_size: null # Feature time span in fps
step_size: null # Feature step size in fps
extraction_fps: null # For original video fps, leave unspecified "null" (None)

# Extraction Parameters
device_ids: [0]  # list of device ids. Use [0, 2] to employ the 0th and 2nd devices.
on_extraction: 'print'  # what to do once the features are extracted. Can be ['print', 'save_numpy', 'save_pickle']
output_path: './output' # where to store results if saved
tmp_path: './tmp' # folder to store the temporary files used for extraction (frames or aud files)
keep_tmp_files: false # to keep temp files after feature extraction.
show_pred: false # to show preds of a model, i.e. on a pre-train dataset for each feature (Kinetics 400)

# config
config: null

# Video paths
file_with_video_paths: null # if the list of videos is large, you might put them in a txt file, use this argument to specify the path
